### ISSUE TITLE
pipelines: not a readable file:bitbucket-pipelines.yml

### ISSUE THREAD

**Issue by pparchure** [ktomk/pipelines#1]
Hello,
This is some great work!
But I am stuck at the first step, while running the YAML file. it says it's not a readable file. My YAML file uses a scala-sbt image with sbt commands in the script. 
Could you please help me with this issue I am facing. Do I do some things differently?

Thanks,
Prathamesh

**Comment by ktomk** [comment]
What is the output of:

~~~
$ ls -al bitbucket-pipelines.yml
~~~

?

**Comment by pparchure** [comment]
I get 
-rw-r--r--. 1 parchp01 cdsguest 461 Aug  1 12:50 bitbucket-pipelines.yml

**Comment by ktomk** [comment]
Hmm, that sounds looks interesting as it seems the file is readable.

Can you operate on it with other tools?

Can you read the file?

Can you change the file?

(all the same shell, in case you wonder)

/e: are you operating on a local file-system?

**Comment by pparchure** [comment]
I can read the file using 
>php  /home-path/bitbucket-pipelines.yml

but can't using the keyword 'pipelines'
I am running this on a linux based machine (local file system)

**Comment by ktomk** [comment]
A nice, and can you go into that directory and execute the following:

~~~
$ php -r 'var_dump(is_readable($argv[1]));' -- bitbucket-pipelines.yml
~~~

Also having the PHP version would be interesting:
~~~
$ php --version
~~~

And last but not least a bit of information about your system:
~~~
$ uname -a
~~~

**Comment by ktomk** [comment]
Ah an you could try the `--debug` switch with the `pipelines` utility. It *might* give a bit more info in your case, I'm not entirely sure though.

**Comment by pparchure** [comment]
It still says not a readable file. 
Has it anything to do with the docker image? is your php script is image specific? mine is sbt scala.

**Comment by pparchure** [comment]
$ php -r 'var_dump(is_readable($argv[1]));' -- bitbucket-pipelines.yml --> bool(false)
$ php --version -->5.4.16
$ uname -a --> x86_64 x86_64 x86_64 GNU/Linux

This is what I get after executing those commands mentioned above. 
Also, I read in your documentation that the image you have used i the default bitbucket-pipeline image. So would that affect reading my yaml file which has a scala-sbt docker image?

**Comment by ktomk** [comment]
> Has it anything to do with the docker image? 

No, the error comes before opening the file `bitbucket-pipeline.yml` for reading. At this point the pipelines utility does not even know which image is referenced inside the file.

> is your php script is image specific?

No, it is not. It just uses any image you name there and will pass that exact name to docker.

> Also, I read in your documentation that the image you have used i the default bitbucket-pipeline image. So would that affect reading my yaml file which has a scala-sbt docker image?

No, as written, the image name is not related to the error message. The error message (also confirmed by the "bool(false)") shows that the pipelines utility is seeing that `bitbucket-pipeline.yml` file as not readable. That is the only reason why you can't go on.

At this point I can only guess what is going on here. Something prevents showing the file as readable. As you say it is the local file-system and in the home-directory could it be that you have SE-Linux or similar running that is preventing showing readability of the file?

This is about your system, not the image. Just to make that explicit again.

Two more tests:
~~~
$ php -r 'var_dump(is_file($argv[1]));' -- bitbucket-pipelines.yml 
~~~
~~~
$ php -ddisplay_errors=1 -derror_reporting=-1 -r 'var_dump(strlen(file_get_contents($argv[1])));' -- bitbucket-pipelines.yml  
~~~

The first should give bool(true) and the second the number of bytes the file has. But please provide the output so I get more insights.

**Comment by pparchure** [comment]
The first command gives : bool(true)
The second command gives: int(146)

Can you confirm the way I should run my .yml file?

**Comment by pparchure** [comment]
Should the pipelines.phar file be inside my cloned project repo?

**Comment by ktomk** [comment]
Okay now I see it, the file has a SELinux security context. Most likely that one is preventing readability.

Check your system configuration and give the pipelines utility enough mojo in the SELinux security context to make `is_readable`  return true.

This should solve your problem.

**Comment by ktomk** [comment]
You can try like this: https://github.com/RainLoop/rainloop-webmail/issues/262#issuecomment-320563460

**Comment by ktomk** [comment]
I'm preparing 0.0.18 which addresses this issue with falling back to a check if the file can be `fopen()`''ed correctly in case `is_readable()` fails.

**Comment by ktomk** [comment]
Version 0.0.18 is out and should be w/o that error on files with SE LInux context that make them appear non-readble by testing if the file can be read anyway. Please test it.

**Comment by ktomk** [comment]
@pparchure Any further feedback on this issue from your end?

**Comment by pparchure** [comment]
@ktomk : sorry for the late response. It worked for me. Can now run the yaml file locally. That's some great work by you. Thank you. I'll stay in touch if I come across any problems in the future. Thanks a ton for your help.
