### ISSUE TITLE
coverage-checker.php deprecated notice

### ISSUE THREAD

**Issue by bkdotcom** [ktomk/pipelines#24]
https://github.com/ktomk/pipelines/blob/3e67dce08f89e038cbef7088ec1002aab93faf6a/lib/build/coverage-checker.php#L53

PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in .../coverage-checker.php on line 53

needs to be either  
`$xml->xpath('.//metrics/@' . $s . 'elements')`  
or  
`$xml->xpath(".//metrics/@{$s}elements")`

**Comment by ktomk** [comment]
Thanks for reporting, [version 0.0.70](https://github.com/ktomk/pipelines/releases/tag/0.0.70) has this now in (+ a couple of other places), see [change log (0.0.70)](https://ktomk.github.io/pipelines/CHANGELOG.html#0070---2023-08-07).

What follows is only for reference, I close the issue, feel free to re-open if there is anything about it.

---

PHP 8.2 [Deprecate ${} string interpolation](https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation) (Created on 2021-03-13)

* Using ${} in strings is deprecated
* Using ${} (variable variables) in strings is deprecated  (“${expr}”, equivalent to (string) ${expr}), e.g. return empty string but do something in expr
