### ISSUE TITLE
More Docker Client Versions

### ISSUE THREAD

**Issue by acederberg** [ktomk/pipelines#26]
Hi @ktomk!

I would like to say I've using your tool to a great degree and really appreciate your supporting it!

I wanted to ask if we could get more versions of docker? Right now the supported versions are

~~~stdout
docker-17.12.0-ce-linux-static-x86_64
docker-18.09.1-linux-static-x86_64
docker-19.03.1-linux-static-x86_64
~~~

according to `pipelines --docker-client-pkgs`. Some scripts require more recent flags, such as `--all-tags` of [docker push](https://docs.docker.com/engine/reference/commandline/push/). I have used this flag successfully in bitbucket pipelines and therefore think some newer versions of the docker client would be helpful. I am not sure exactly which version is used in bitbucket. 

Also I would like to state that I am using pipelines version `0.0.68` which appears to be the most recent tag.

**Comment by ktomk** [comment]
Hi @acederberg,

thanks for reaching out. If you could run

~~~
docker version --format "client: {{.Client.Version}} / server: {{.Server.Version}}"
~~~
_([pipeline example](https://github.com/ktomk/pipelines/blob/master/bitbucket-pipelines.yml#L198C16-L198C99))_

that should shed more light into the current version, I cant look atm. This would help to not miss the one you're looking for.

I'll look into this, but in any case a procedure is also part of the docs if you need more control yourself (e.g. own binaries, like just build): https://ktomk.github.io/pipelines/doc/PIPELINES-HOWTO-DOCKER-CLIENT-BINARY.html

**Comment by acederberg** [comment]
I added this to one of my pipelines and ran it on bitbucket. I got the following out of `docker version`:

~~~sh
Client:
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:17:06 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       5d6db84
  Built:            Tue Apr  4 18:23:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a6
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
~~~

@ktomk

**Comment by ktomk** [comment]
@acederberg please find version 0.0.69 released: https://ktomk.github.io/pipelines/CHANGELOG.html#0069---2023-08-05 - docker client 20.10.24 is in and the new default. it worked on my end, so I close the issue, but please let me know if it worked for you.

**Comment by acederberg** [comment]
@ktomk I thought I already commented this but I turns out I had not. Everything works as I expect, thank you again!

**Comment by ktomk** [comment]
@acederberg Sweet and sound. Thanks for your feedback, much appreciated. And not to forget your additional efforts with this issue, it helped me a lot to get it going! I hope the new default settles well, if not, don't be shy to comment here or open a new issue, you're welcome!
